name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch if different

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Adjust this command if your build process is different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Specify your build output directory
