name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any specific build steps for your site here
      # For example, if using a static site generator or npm to build
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Build site
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust if you have a build directory, e.g., ./build or ./dist
